import User from "../models/User.js";
import Token from "../models/Token.js";
import bcrypt from "bcryptjs";
// import User from "../models/User.js";
export const getAllUsers = async (req, res) => {
  try {

    // Get all users except passwords
    const users = await User.find()
      .select("-password")
      .sort({ createdAt: -1 });

    // Build response with queue information
    const usersWithStats = await Promise.all(

      users.map(async (user) => {

        // Total tokens generated by this user
        const totalTokens = await Token.countDocuments({
          user: user._id,
        });

        // Latest token
        const latestToken = await Token.findOne({
          user: user._id,
        })
          .sort({ createdAt: -1 })
          .populate("branch", "name");

        return {

          _id: user._id,

          name: user.name,

          email: user.email,

          role: user.role,

          joined: user.createdAt,

          totalTokens,

          latestToken: latestToken
            ? latestToken.tokenNumber
            : "-",

          tokenStatus: latestToken
            ? latestToken.status
            : "-",

          branch: latestToken?.branch?.name || "-",

        };

      })

    );

    res.json(usersWithStats);

  } catch (error) {

    res.status(500).json({
      message: error.message,
    });

  }
};
export const changePassword = async (req, res) => {

  try {

    const {
      currentPassword,
      newPassword,
      confirmPassword,
    } = req.body;

    if (newPassword !== confirmPassword) {

      return res.status(400).json({
        message: "Passwords do not match",
      });

    }

    const user = await User.findById(req.user._id);

    const isMatch = await bcrypt.compare(
      currentPassword,
      user.password
    );

    if (!isMatch) {

      return res.status(400).json({
        message: "Current password is incorrect",
      });

    }

    const salt = await bcrypt.genSalt(10);

    user.password = await bcrypt.hash(
      newPassword,
      salt
    );

    await user.save();

    res.json({
      message: "Password updated successfully",
    });

  }

  catch (error) {

    res.status(500).json({
      message: error.message,
    });

  }

};